project:
  type: website
  output-dir: docs # Carpeta de salida para GitHub Pages

website:
  title: "quarto-website"
  navbar:
    left:
      # Asumiendo que crearás un archivo index.qmd en la RAIZ
      - href: index.qmd
        text: Home
      # Referencia a tu archivo de análisis dentro de la carpeta scripts
      - href: scripts/pardeamiento_uva.qmd
        text: Analisis

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true