project:
  type: website
  output-dir: docs

website:
  title: "Sensibilidad al pardeamiento del raquis de uva de mesa"
  navbar:
    right:
      - text: "Inicio"
        href: index.qmd
      - text: "Metodología"
        href: metodologia.qmd
      - text: "Resultados"
        href: resultados.qmd
      - text: "Código"
        href: scripts/pardeamiento_uva.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
